services:
  api:
    build: .
    container_name: timeoff-microservice
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - sqlite_data:/usr/src/app/data
    environment:
      - NODE_ENV=development
    command: npm run start:dev

volumes:
  sqlite_data:
